### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Golrathcr** [Luxocracy/NeatPlates#21] opened 2018-09-21 05:04 UTC
I'm sorry if this is not the proper place for this but I was wondering if you could add a widget for displaying arena 1 2 3 to the left or right side next to the nameplate, or possibly an option to replace names with Arena ID when inside arena. I know there is currently a way to add Arena ID as status text with health and power displaying but I find it makes the nameplate look very crowded and hard to read when nameplate size is scaled down. Thank you.

**Comment by Golrathcr** [comment] 2018-11-01 21:50
Thanks for the update. I tried the status text and it currently appears to show all 3 players as arena 2.

**Comment by Luxocracy** [comment] 2018-11-01 22:30
Whoops, looks like I accidentally had some code left over from when I was testing it, which sets it as 2.
[Should be fixed now](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.9b).

**Comment by Golrathcr** [comment] 2018-11-01 23:56
Works now, thanks for the update!

**Comment by Luxocracy** [comment] 2021-05-29 07:04
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.

**Closed by Luxocracy** 2021-05-29 07:04 UTC
Labels: Feature Request
