### ISSUE TITLE
Unit Filter - unit scale doesn't work correctly?

### ISSUE THREAD

**Issue by yah467958** [Luxocracy/NeatPlates#182] opened 2019-12-10 19:16 UTC
Hello!

As in title, when I'm changing unit scale in Unit Filter nothing happening. Unit Opacity working and changing opacity instantly but unit scale - nothing at all.

Also is it possible to separate filter for enemy/friendly npc into friendly/enemy pets and friendly/enemy mobs? Because right now if we mark enemy npc it's changing everything - mobs, pets and enemy guards for example.

**Comment by Luxocracy** [comment] 2019-12-14 12:02
It was indeed not working as intended, as it only ever worked when **override** was checked, must have been like that for quite a while...

This should be fixed as of the latest release. This release also includes a separation of the _Friendly/Enemy NPC_ filter into NPC/Pets.

**Comment by yah467958** [comment] 2019-12-14 13:41
I'm glad to hear that :dancer:

**Comment by yah467958** [comment] 2019-12-14 16:09
I checked it and everything working perfect.

But i'm not quite sure how filtering for players working... it's filtering enemy or friendly players? If it's working for both, once again can you separate it for enemy/friendly? :)

**Closed** 2019-12-28 11:38 UTC
