### ISSUE TITLE
A rare bug about hiding original Blizzard nameplate

### ISSUE THREAD

**Issue by Nukme** [Luxocracy/NeatPlates#45] opened 2018-11-26 03:33 UTC
Hi, I want to report a bug that has been there for the whole Legion expansion. I'll try my best to describe it and expect it to be treated as some low-priority bug that you could take time to look into it and decide whether to fix it .

When the game transited from WOD to LEG, Blizzard introduced the re-worked nameplate system, including new settings and new artwork, which caused many problems for TP to hide the Blizzard nameplates at that time. I reported many related bugs back then and the original author was pushing out updates frequently to fix them. Before the author's sudden absence from TP,  he left the last release for Legion (6.18.11, Oct 30, 2016), in which he did the last update on hiding Blizzard nameplate that worked for most of the in-game scenes. 

However, during the following LEG expansion, I observed there's still a bug that occurs very rarely. When a enemy player, with pets aside (hunters, warlocks), enters my screen for the first time, there's a very high chance that the Blizzard nameplate will show alongside the TP nameplate. And if I just move my mouse cursor over it, the Blizzard nameplate would be gone.

In BfA that could happen by a very low chance, but I have noticed a relatively reliable way to reproduce the bug. In BfA 5-man dungeon Kings' Rest, there's a kind of trash called Spectral Witch Doctor on the hallway from #2 to #3 boss. When this specific witch doctor use its ability and summons a healing tide totem, there's a very high chance that the Blizzard nameplate would show up overlapped beneath the TP nameplate. 

I assume this has to be related to how TP hides Blizzard nameplate but I don't dive in too much to find out how the bug works. And I always think maybe the best way is to implement a more clean and effective hiding method.

**Comment by Luxocracy** [comment] 2018-11-26 09:41
I've kinda known about this for a while, it happens quite regularly with the players own healthbar if that is enabled. Hence why TPC doesn't attempt to skin that bar anymore because the root cause has not been found.

I also know that this isn't an issue exclusive to TidyPlates. I've had multiple guildies with different nameplate addons mention the same weird issue happening in Kings Rest. 

From what I remember of trying to deal with this issue when it was related to the players own healthbar, the only method that showed any result was to try and prevent the blizzard frame from showing by messing with the "show" function. However, in doing this, because it is a blizzard protected function, it would cause that function to be tainted and cause an error to be displayed for the user.
So my guess is that it has something to do with the blizzard plates calling their show function later than usual sometimes causing the weird behaviour.

**Comment by Luxocracy** [comment] 2018-11-26 10:41
So there is actually something that could be done, which I think would prevent this from happening and that is to hide the children of the plate in the `OnUpdate` function each time it is called.
This is something that is already done if the plate requests an update, which is why it goes away when you mouseover a unit as it then requests an update, or the health of the unit changes.

By moving `plate:GetChildren():Hide()` from line 167 in _TidyPlatesCore.lua_ out of the if statement to something like line 170 it prevents the the blizzard plate from ever showing. I have no idea what kind of performance impact this would have, but from brief testing there isn't one that I can notice.

**Comment by Aufladi** [comment] 2019-03-12 01:17
Hey, I know that its unlikely to be fixed but it would be great if you could look into that bug again.
Its literally the only thing i dislike about Neat Plates. 
The bug seems to occur more often when engaged with enemy players (I play lots of arena). 
If I "retarget" the player with the bugged nameplate (drop target or swap to a different target and target the previous target again) the blizzard default nameplate disappears again.
Thx in advance

**Comment by Luxocracy** [comment] 2019-03-12 08:08
As mentioned above I've been hesitant to implement the fix for this because of being unsure of what the impact on performance could be. Though, honestly I don't think there would be one and I'm just being overly cautious/paranoid. 
But if it is happening as often as you say then I'll push an update with the fix and this shouldn't happen any more. Because in my mind this has been something that rarely ever happens, as I've not seen it in a long time, that could have a negative impact on that addon.

**Closed** 2019-05-26 09:12 UTC
Labels: Unlikely to be added/fixed
