### ISSUE TITLE
Constant errors randomly appearing.

### ISSUE THREAD

**Issue by Yarvillian** [Luxocracy/NeatPlates#277] opened 2020-12-30 03:53 UTC
2265x NeatPlates\NeatPlatesUtility.lua:296: attempt to index local 'texture' (a nil value)
[string "@NeatPlates\NeatPlatesUtility.lua"]:296: in function <NeatPlates\NeatPlatesUtility.lua:277>
[string "@NeatPlatesWidgets\QuestWidget.lua"]:10: in function <NeatPlatesWidgets\QuestWidget.lua:7>
[string "@NeatPlatesWidgets\QuestWidget.lua"]:37: in function `UpdateContext'
[string "@NeatPlatesHub\functions\Widgets.lua"]:690: in function `OnContextUpdate'
[string "@NeatPlates\NeatPlatesCore.lua"]:659: in function <NeatPlates\NeatPlatesCore.lua:644>
[string "@NeatPlates\NeatPlatesCore.lua"]:524: in function <NeatPlates\NeatPlatesCore.lua:515>
[string "@NeatPlates\NeatPlatesCore.lua"]:198: in function <NeatPlates\NeatPlatesCore.lua:171>

Locals:
unit = <table> {
 guid = "Creature-0-4231-2296-28754-164407-00006BF711"
 isMouseover = false
 class = ""
 rawName = "Sludgefist"
 threatSituation = "LOW"
 red = 0.999998
 isInCombat = false
 isDangerous = true
 alphaMult = 0.149020
 isMini = false
 isElite = true
 pvpname = "Sludgefist"
 levelcolorRed = 0.500000
 levelcolorBlue = 0.500000
 isPet = false
 isBoss = true
 level = -1
 isFocus = false
 isTrivial = true
 isTarget = true
 levelcolorGreen = 0.500000
 powermax = 100
 unitid = "nameplate1"
 isTapped = false
 type = "NPC"
 blue = 0
 power = 0
 name = "Sludgefist"
 isMarked = false
 healthmax = 27404710
 showName = true
 health = 27404710
 green = 0
 style = "Default"
 threatValue = 0
 isCasting = false
 reaction = "HOSTILE"
}
unitid = "nameplate1"
questName = "Ephidale"
questUnit = nil
questProgress = nil
questList = <table> {
 Ephidale = <table> {
 }
 Castle Nathria: Getting a Head = <table> {
 }
 Bearnârdo = <table> {
 }
 Yarv = <table> {
 }
 Cleantigers = <table> {
 }
 Hunternoodlë = <table> {
 }
}
questTexture = <table> {
 628564 = true
 3083385 = false
}
objectiveCount = 3
questCompleted = <table> {
 1 = false
 2 = false
 3 = false
 4 = false
 5 = false
 6 = false
 7 = false
 8 = false
 9 = false
 10 = false
}
textureIds = ", 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385"
(for index) = 31
(for limit) = 35
(for step) = 1
line = 31
texture = nil
(*temporary) = "NeatPlatesScanningTooltipTexture31"
(*temporary) = nil
(*temporary) = "31"
(*temporary) = 0
(*temporary) = true
(*temporary) = <table> {
 2/4 Sludgefist's Head = false
 texture = ", 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385, 3083385"
}
(*temporary) = 0
(*temporary) = "attempt to index local 'texture' (a nil value)"
TooltipScanner = NeatPlatesScanningTooltip {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 textLeft1Font = "GameTooltipHeaderText"
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:433
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:465
 RightEdge = <unnamed> {
 }
 textRight2Font = "GameTooltipText"
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:452
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:390
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
 TextLeft1 = NeatPlatesScanningTooltipTextLeft1 {
 }
 0 = <userdata>
 BottomEdge = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:225
 BottomOverlay = <unnamed> {
 }
 backdropInfo = <table> {
 }
 Center = <unnamed> {
 }
 textRight1Font = "GameTooltipHeaderText"
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:321
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
 updateTooltip = 0.200000
 textLeft2Font = "GameTooltipText"
 TopEdge = <unnamed> {
 }
 TextRight2 = NeatPlatesScanningTooltipTextRight2 {
 }
 TextLeft2 = NeatPlatesScanningTooltipTextLeft2 {
 }
 BottomRightCorner = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:289
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 TextRight1 = NeatPlatesScanningTooltipTextRight1 {
 }
}
ScannerName = "NeatPlatesScanningTooltip"
GetTooltipLineText = <function> defined @NeatPlates\NeatPlatesUtility.lua:269

**Comment by Luxocracy** [comment] 2020-12-30 12:17
Seems like this was caused by some debug code not properly checking if things existed or not, this should be resolved in the latest update. A bit surprising I haven't experienced this error myself.

**Comment by Yarvillian** [comment] 2021-01-06 04:15
Continuing to happen but only with Sludgefist!!

**Comment by Luxocracy** [comment] 2021-01-06 12:31
Seems this issue was in more than one place, the latest release should hopefully have resolved this properly this time.

**Comment by Luxocracy** [comment] 2021-05-29 07:13
Doing a bit of cleaning up and closing issues that are stale, or has been resolved by never confirmed to be resolved. If you believe this is in error, please comment and I'll re-open the issue again.

**Closed by Luxocracy** 2021-05-29 07:13 UTC

**Comment by Yarvillian** [comment] 2021-05-30 13:24
That’s my fault. Should have closed it. Thank you :D
