### ISSUE TITLE
Lua error with latest update

### ISSUE THREAD

**Issue by silverhawke249** [Luxocracy/NeatPlates#308] opened 2021-06-08 02:50 UTC
![image](https://user-images.githubusercontent.com/50395934/121115089-47563f80-c847-11eb-9067-8d7850aac391.png)

not sure what happened, i just updated and now i get these Lua errors every so often.

**Comment by l3uGsY** [comment] 2021-06-08 05:26
Yes, and they are very persistent forcing you to turn off the addon.

**Comment by Luxocracy** [comment] 2021-06-08 06:12
Closing this as this is a duplicate of https://github.com/Luxocracy/NeatPlates/issues/307

**Closed by Luxocracy** 2021-06-08 06:12 UTC
