### ISSUE TITLE
Widget, script ran too long

### ISSUE THREAD

**Issue by TheKrowi** [Luxocracy/NeatPlates#275] opened 2020-12-17 21:17 UTC
Doing Torghast froze my game twice now so far. After combat ends I get this error:

```
Message: Interface\AddOns\NeatPlatesHub\functions\Widgets.lua:421: script ran too long
Time: Thu Dec 17 20:35:49 2020
Count: 1
Stack: Interface\AddOns\NeatPlatesHub\functions\Widgets.lua:421: script ran too long
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\NeatPlatesHub\functions\Widgets.lua"]:421: in function <Interface\AddOns\NeatPlatesHub\functions\Widgets.lua:419>
[string "@Interface\AddOns\NeatPlatesHub\functions\Widgets.lua"]:478: in function <Interface\AddOns\NeatPlatesHub\functions\Widgets.lua:460>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\NeatPlatesWidgets\AuraWidget.lua"]:315: in function <Interface\AddOns\NeatPlatesWidgets\AuraWidget.lua:256>
[string "@Interface\AddOns\NeatPlatesWidgets\AuraWidget.lua"]:466: in function <Interface\AddOns\NeatPlatesWidgets\AuraWidget.lua:459>
[string "@Interface\AddOns\NeatPlatesWidgets\AuraWidget.lua"]:487: in function `Expire'
[string "@Interface\AddOns\NeatPlatesWidgets\WidgetCore.lua"]:61: in function <Interface\AddOns\NeatPlatesWidgets\WidgetCore.lua:52>

Locals: errMsg = "Interface\AddOns\NeatPlatesHub\functions\Widgets.lua:421: script ran too long"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}
```

**Comment by Luxocracy** [comment] 2020-12-23 16:34
First of all, sorry for not having responded to this, I though I already had.

This is a quite rare issue that I've only heard of a handful of times, and is something I'm still trying to resolve. But the nature of the issue, and that I've never been able to replicate it myself, makes it quite hard to pinpoint the root cause. The freezing is quite odd and something I think I've only heard of once before, and at the time I figured the freeze might have caused the error and not the other way around. 

But it might not have been, so something you could do is try to reduce the amount of things the aura widget has to process each time by disabling some features of it. And a sort of hidden thing you could do is change the _Precise Aura Duration Threshold_ to 0, this will cause the aura widget to have to update things less.

**Comment by Luxocracy** [comment] 2020-12-26 14:59
I've posted an update on this issue here #242, also gonna close this issue as they are the same issue and it'd be better to consolidate this into one issue.

**Closed by Luxocracy** 2020-12-26 14:59 UTC
